name: release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    steps:

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure cache paths
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Restore Go build cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Restore Go mod cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Download deps
        run: go mod download

      - name: Build controller
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o promrule-exporter ./main.go

      - name: Export release version
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . -t slamdev/promrule-exporter:${{ env.RELEASE_VERSION }}

      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u slamdev --password-stdin

      - name: Push Docker image
        run: docker push slamdev/promrule-exporter:${{ env.RELEASE_VERSION }}
